/**
 * Neko的AI白嫖指南 - 站点数据库
 * 整理日期: 2026
 * 包含44个优质AI大模型API中转、免费对话与白嫖额度站点
 */

const SITE_CATEGORIES = {
  all: { name: "全部站点", icon: "🐾" },
  featured: { name: "🌟 精选爆款", icon: "🎁" },
  api: { name: "⚡ API中转站", icon: "⚡" },
  coding: { name: "💻 代码专精", icon: "💻" },
  chat: { name: "💬 免配置直聊", icon: "💬" },
  drawing: { name: "🎨 绘图与创意", icon: "🎨" },
  fast: { name: "🌐 高速直连", icon: "🚀" },
};

const HOT_TAGS = [
  "注册送额",
  "每日签到",
  "GPT-4o",
  "Claude-3.5",
  "Cursor可用",
  "Web免配置",
  "二次元绘图",
  "国内直连",
  "多模型聚合",
  "超低费率",
  "高并发",
  "长文本",
];

const SITES_DATA = [
  {
    id: 1,
    name: "AgentRouter",
    category: "api",
    url: "https://agentrouter.org/register?aff=5OIh",
    baseUrl: "https://agentrouter.org/v1",
    badge: "智能体专选",
    badgeType: "hot",
    tags: ["注册送额", "多模型聚合", "高并发", "Agent专供"],
    desc: "专为智能体与自动化工作流量身打造的 API 网关，多模型聚合热备，路由响应毫秒级。",
    freePerk: "新用户注册即送初始调用额度，支持全系列主力模型"
  },
  {
    id: 2,
    name: "JustWoker API",
    category: "api",
    url: "https://api.justwoker.icu/register?aff=8ygR",
    baseUrl: "https://api.justwoker.icu/v1",
    badge: "轻量极速",
    badgeType: "speed",
    tags: ["NewAPI", "轻量快速", "开发者友好", "国内直连"],
    desc: "稳定轻量的 NewAPI 接口平台，极简界面管理，适合个人开发者日常接入与小项目调试。",
    freePerk: "注册赠送免费测试 Token，直连不卡顿"
  },
  {
    id: 3,
    name: "GoRouter",
    category: "api",
    url: "https://gorouter.app/sign-up?aff=woTg",
    baseUrl: "https://gorouter.app/v1",
    badge: "全球加速",
    badgeType: "speed",
    tags: ["全球加速", "企业级并发", "高可用", "多模型聚合"],
    desc: "全球多节点边缘路由加速，企业级并发吞吐，专为高负载与自动化任务设计的大模型入口。",
    freePerk: "注册赠送体验金，全球节点智能就近接入"
  },
  {
    id: 4,
    name: "TabiToken",
    category: "fast",
    url: "https://tabitoken.com/sign-up?aff=Zknh",
    baseUrl: "https://tabitoken.com/v1",
    badge: "新人礼包",
    badgeType: "hot",
    tags: ["Token分发", "超低费率", "新人礼包", "注册送额"],
    desc: "高性价比的 Token 分发与中转平台，按需划扣费率透明，新手起步毫无门槛。",
    freePerk: "完成注册即送启动额度包，支持绑定主流客户端"
  },
  {
    id: 5,
    name: "福卡 API (FuKa)",
    category: "api",
    url: "https://api.fuka.win/sign-up?",
    baseUrl: "https://api.fuka.win/v1",
    badge: "口碑公益",
    badgeType: "free",
    tags: ["公益优选", "全模型支持", "性价比", "GPT-4o"],
    desc: "国内口碑极佳的低价与公益性 API 站点，主力模型一应俱全，稳定性出众。",
    freePerk: "注册即送新手配额，全系列主流大模型开箱即测"
  },
  {
    id: 6,
    name: "猫猫 API (CatCat)",
    category: "api",
    url: "https://api.catcat.top/sign-up?aff=SNTc",
    baseUrl: "https://api.catcat.top/v1",
    badge: "萌系稳定",
    badgeType: "cute",
    tags: ["萌系稳定", "Claude-3.5", "极速响应", "注册送额"],
    desc: "猫系二次元萌感设计，后台通道稳定且响应极快，深度适配各种沉浸式翻译与客户端。",
    freePerk: "新猫咪注册立享初始免费额度，Claude 3.5 丝滑调用"
  },
  {
    id: 7,
    name: "HCNsec API",
    category: "fast",
    url: "https://api.hcnsec.cn/sign-up?aff=nJQnaff=KSK9",
    baseUrl: "https://api.hcnsec.cn/v1",
    badge: "安全高防",
    badgeType: "safe",
    tags: ["安全防护", "国内直连", "多协议", "稳定可靠"],
    desc: "具备安全防护与国内高速直连专线的 API 服务，多重容灾备份，不用担心连接中断。",
    freePerk: "注册赠送新手免费试用额度，国内网络直连低延迟"
  },
  {
    id: 8,
    name: "SharedChat",
    category: "chat",
    url: "https://new.sharedchat.cc/list/#/register?i=4l71o",
    baseUrl: "https://new.sharedchat.cc",
    badge: "免配置直聊",
    badgeType: "web",
    tags: ["Web免配置", "ChatGPT共享", "多账号", "开箱即用"],
    desc: "网页版大模型账号池共享平台，免去本地任何客户端配置，打开浏览器直接体验官方对话界面。",
    freePerk: "注册即送免费体验次数，免自备 API Key 畅聊"
  },
  {
    id: 9,
    name: "洛谷 AI (Luogu)",
    category: "coding",
    url: "https://ai.luogu.me/sign-up?aff=KI3Z",
    baseUrl: "https://ai.luogu.me/v1",
    badge: "算法编程",
    badgeType: "code",
    tags: ["算法编程", "代码补全", "Cursor可用", "学术生态"],
    desc: "由知名 OJ 生态衍生的高质量 AI 镜像服务，针对代码逻辑、算法竞赛与学术研究深度调优。",
    freePerk: "注册送额度，代码调试与学术问答体验极佳"
  },
  {
    id: 10,
    name: "丑猫 API (UglyCat)",
    category: "api",
    url: "https://api.uglycat.cc/register?aff=iyZz",
    baseUrl: "https://api.uglycat.cc/v1",
    badge: "极低延迟",
    badgeType: "speed",
    tags: ["高并发", "GPT-4o", "Claude-3.5", "极速响应"],
    desc: "名字低调实力超强的 API 中转站，全天候超低首字延迟，支持各种最新旗舰大模型。",
    freePerk: "注册即可白嫖体验金，支持高并发并发调用"
  },
  {
    id: 11,
    name: "北执 API (Sylu)",
    category: "fast",
    url: "https://beizhi.sylu.cc/sign-up?aff=IBxl",
    baseUrl: "https://beizhi.sylu.cc/v1",
    badge: "高校公益",
    badgeType: "free",
    tags: ["高校社区", "稳定长效", "公益赞助", "国内直连"],
    desc: "高校技术社团与开发者社区联合维护的公益 API 站点，持续长效运营，良心厚道。",
    freePerk: "长期提供公益免费测试额度，社群活跃互助"
  },
  {
    id: 12,
    name: "BlueSMinds API",
    category: "fast",
    url: "https://api.bluesminds.com/sign-up?aff=uanj",
    baseUrl: "https://api.bluesminds.com/v1",
    badge: "多模态专区",
    badgeType: "safe",
    tags: ["多模态", "高防集群", "智能路由", "长文本"],
    desc: "采用分布式高防集群架构，不仅支持纯文本模型，还深度支持 Vision 视觉分析与长文档理解。",
    freePerk: "新用户注册享大额试用额度，支持图片解析"
  },
  {
    id: 13,
    name: "HelpCoder",
    category: "coding",
    url: "https://helpcoder.cc/register?aff=jUgZ",
    baseUrl: "https://helpcoder.cc/v1",
    badge: "代码神器",
    badgeType: "code",
    tags: ["Cursor可用", "编程助手", "代码生成", "Claude-3.5"],
    desc: "专为 Cursor、VS Code Continue、Cline 等开发工具定制的高吞吐代码 API 供应商。",
    freePerk: "注册即送额度，完美适配 Cursor 代码补全与 Agent"
  },
  {
    id: 14,
    name: "新建鸭 (XinJianYa)",
    category: "featured",
    url: "https://new.xinjianya.top/register?aff=96Oh",
    baseUrl: "https://new.xinjianya.top/v1",
    badge: "每日签到",
    badgeType: "hot",
    tags: ["每日签到", "注册送额", "全网低价", "超低费率"],
    desc: "每日签到即可领额度的白嫖党大本营！长久运营，价格极低，深受白嫖玩家好评。",
    freePerk: "注册即送初始额度 + 每天打卡签到免费领 Token"
  },
  {
    id: 15,
    name: "SupXH Free API",
    category: "featured",
    url: "https://free.supxh.xin/register?code=UEPUUR",
    baseUrl: "https://free.supxh.xin/v1",
    badge: "纯白嫖站",
    badgeType: "free",
    tags: ["纯白嫖专区", "零门槛", "注册送额", "每日签到"],
    desc: "专为零成本体验打造的 Free 镜像中转站，零门槛入门，无需任何复杂认证。",
    freePerk: "注册输入邀请码立得大额免费额度，零成本直接起飞"
  },
  {
    id: 16,
    name: "True-SOTA",
    category: "api",
    url: "https://true-sota.com/register?aff=Q3C4T6PUQLDL",
    baseUrl: "https://true-sota.com/v1",
    badge: "SOTA顶尖",
    badgeType: "speed",
    tags: ["SOTA顶模", "前沿推理", "科研首选", "Claude-3.5"],
    desc: "聚焦全球 State-Of-The-Art 顶尖前沿大模型，推理速度快，适合对回复质量要求严苛的高级场景。",
    freePerk: "注册送额体验顶尖 SOTA 思考与推理模型"
  },
  {
    id: 17,
    name: "今夕 API (JinShi)",
    category: "fast",
    url: "https://new.jinshi.xin/sign-up?aff=6oB2",
    baseUrl: "https://new.jinshi.xin/v1",
    badge: "线路冗余",
    badgeType: "safe",
    tags: ["多线路负载", "稳定持久", "开箱即用", "国内直连"],
    desc: "拥有完善的多线路负载均衡与容灾切换机制，拒绝断连，日常主力使用体验极其平稳。",
    freePerk: "注册即可获赠使用额度，支持一键配置 NextChat"
  },
  {
    id: 18,
    name: "CamelHub",
    category: "api",
    url: "https://api.camel-hub.com/register?aff=TO1b",
    baseUrl: "https://api.camel-hub.com/v1",
    badge: "Agent适配",
    badgeType: "code",
    tags: ["Agent协作", "开发套件", "高并发", "多模型聚合"],
    desc: "针对多智能体协同（Multi-Agent）、AutoGPT 等复杂架构深度优化的中转网络。",
    freePerk: "注册立享开发者福利包，轻松驱动多智能体"
  },
  {
    id: 19,
    name: "网易云风 (WYY22)",
    category: "fast",
    url: "https://www.wyy22.com/sign-up?aff=YZL3",
    baseUrl: "https://www.wyy22.com/v1",
    badge: "小白友好",
    badgeType: "free",
    tags: ["公益普惠", "新手友好", "NextChat适配", "国内直连"],
    desc: "极简清爽的新手友好型中转站，配置说明清晰，复制 API 密钥填入客户端即可秒速使用。",
    freePerk: "新手注册即领赠额，免翻墙顺畅连线"
  },
  {
    id: 20,
    name: "NexusVAI",
    category: "chat",
    url: "https://www.nexusvai.xyz/chat/?invite=1509213c-2c4a-4b10-9626-fa8689d4795f",
    baseUrl: "https://www.nexusvai.xyz",
    badge: "全能工作台",
    badgeType: "web",
    tags: ["Web免配置", "网页直接聊", "多模型切换", "智能对话"],
    desc: "现代化的在线 AI 对话工作台，免去任何客户端配置，注册后在网页端直接随心所欲畅聊。",
    freePerk: "邀请链接直达注册，免客户端开箱即聊"
  },
  {
    id: 21,
    name: "7891VIP",
    category: "drawing",
    url: "https://7891vip.cc.cd/login?view=reg&aff=gioR",
    baseUrl: "https://7891vip.cc.cd/v1",
    badge: "VIP特权",
    badgeType: "hot",
    tags: ["VIP尊享", "超大带宽", "逆向官转", "长文本"],
    desc: "提供超大带宽的专属 VIP 级通道，涵盖官转与精细逆向接口，保障高负载时刻依然丝滑响应。",
    freePerk: "注册进入尊享通道，享受高优先级调用与初始赠额"
  },
  {
    id: 22,
    name: "Rinko AI (NAI)",
    category: "drawing",
    url: "https://nai.rinko.ai/sign-up?aff=Fr7j",
    baseUrl: "https://nai.rinko.ai/v1",
    badge: "二次元生图",
    badgeType: "cute",
    tags: ["二次元绘图", "NovelAI专精", "动漫生图", "绘画"],
    desc: "专注于 NovelAI 优质二次元动漫绘画的中转站点，画风惊艳唯美，支持各类二次元魔法咒语！",
    freePerk: "注册获赠生图积分，二次元画师与萝莉控狂喜"
  },
  {
    id: 23,
    name: "Orevx AI",
    category: "chat",
    url: "https://orevx.ai/login?mode=register&inviteCode=NWO170LO",
    baseUrl: "https://orevx.ai",
    badge: "现代交互",
    badgeType: "web",
    tags: ["Web免配置", "文档分析", "全能助手", "长文本"],
    desc: "UI 设计极其惊艳的企业级对话平台，具备知识库问答、长文档分析以及代码编写等全能本领。",
    freePerk: "输入专属邀请码注册，立享海量对话额度"
  },
  {
    id: 24,
    name: "TokenBom (Token炸弹)",
    category: "featured",
    url: "https://tokenbom.com/login?mode=register&invite=SS-9B89C913",
    baseUrl: "https://tokenbom.com/v1",
    badge: "福利爆仓",
    badgeType: "hot",
    tags: ["注册送额", "大额赠送", "海量Token", "福利爆仓"],
    desc: "名副其实的 Token 投弹手！注册赠送的额度极为丰厚，活动多，是白嫖圈的必冲神站。",
    freePerk: "注册输入邀请码立送大额体验礼包，真正吃到饱"
  },
  {
    id: 25,
    name: "CreitAPI",
    category: "drawing",
    url: "https://myapi.creitingameplays.com/sign-up?aff=oV4h",
    baseUrl: "https://myapi.creitingameplays.com/v1",
    badge: "极客游戏",
    badgeType: "code",
    tags: ["极客专用", "游戏NPC", "低延迟", "多模型聚合"],
    desc: "针对游戏 NPC 对话、剧情互动与极客轻应用优化，响应速度快，接口兼容性极强。",
    freePerk: "注册赠送体验金，适合游戏剧情与互动剧本接入"
  },
  {
    id: 26,
    name: "NOFX One",
    category: "chat",
    url: "https://nofx.one/zh-CN/sign-in?ref=17AE4SJY",
    baseUrl: "https://nofx.one",
    badge: "中文工作台",
    badgeType: "web",
    tags: ["Web免配置", "一体化平台", "网页直接聊", "中文界面"],
    desc: "本土化深度优化的 Web AI 工作台，自带精美交互体验，全方位支持各类流行顶尖模型。",
    freePerk: "注册即送额度，网页端免配置即开即用"
  },
  {
    id: 27,
    name: "KK Token",
    category: "fast",
    url: "https://kktoken.cc/sign-up?aff=5eUk",
    baseUrl: "https://kktoken.cc/v1",
    badge: "极速响应",
    badgeType: "speed",
    tags: ["极简轻量", "分发稳定", "快速到账", "超低费率"],
    desc: "轻量化 Token 分发节点，无冗余臃肿功能，直奔主题，快速生成 Key 即可调用。",
    freePerk: "注册即领试用配额，轻量实用"
  },
  {
    id: 28,
    name: "AeroLink",
    category: "fast",
    url: "https://aerolink.lat/register?ref=ZY8-XVA",
    baseUrl: "https://aerolink.lat/v1",
    badge: "跨境专线",
    badgeType: "speed",
    tags: ["海外加速", "跨境专线", "网络优化", "低抖动"],
    desc: "采用专线网络直达海外大模型官方端点，极低网络抖动与丢包率，保证长文输出不中断。",
    freePerk: "注册即送免费额度，体验专线极速下发"
  },
  {
    id: 29,
    name: "CheapCodex",
    category: "coding",
    url: "https://api.cheapcodex.online/register?aff=NRS3ZWZLHSZN",
    baseUrl: "https://api.cheapcodex.online/v1",
    badge: "超平价代码",
    badgeType: "code",
    tags: ["超平价代码", "Cursor可用", "Claude-Code", "极速补全"],
    desc: "专为代码狂人打造的超平价服务，代码模型调用费用低廉，全面兼容各类 IDE 辅助插件。",
    freePerk: "新注册用户赠送代码测试额度，写代码丝般顺滑"
  },
  {
    id: 30,
    name: "Denxio API",
    category: "api",
    url: "https://api.denxio.top/register?invite_code=JZD9ERE7GV4C",
    baseUrl: "https://api.denxio.top/v1",
    badge: "热备网关",
    badgeType: "safe",
    tags: ["聚合网关", "多渠道热备", "高可用", "高并发"],
    desc: "高可用架构网关，后台配置多通道热备策略，单渠道波动自动秒切，稳定性行业领先。",
    freePerk: "注册赠送大额额度，高并发调用不掉线"
  },
  {
    id: 31,
    name: "Vyce AI",
    category: "chat",
    url: "https://vyceai.com/signup?ref=VYCE_WPT6BH",
    baseUrl: "https://vyceai.com",
    badge: "前沿UI",
    badgeType: "web",
    tags: ["Web免配置", "前沿UI", "创意灵感", "智能工作流"],
    desc: "设计感爆棚的 AI 创作中心，专为设计师与文案策划打造，交互体验如同未来科技应用。",
    freePerk: "注册即享专属免费使用点数，免装软件直接聊"
  },
  {
    id: 32,
    name: "KiosAPI",
    category: "api",
    url: "https://kiosapi.com/sign-up?aff=KhTb",
    baseUrl: "https://kiosapi.com/v1",
    badge: "企业级吞吐",
    badgeType: "speed",
    tags: ["企业级吞吐", "极速响应", "稳定输出", "GPT-4o"],
    desc: "企业级吞吐能力的高性能 API 平台，支持超多并发，首字吐出速度快如闪电。",
    freePerk: "注册即可白嫖体验金，适合批量并发调用测试"
  },
  {
    id: 33,
    name: "McGrox",
    category: "fast",
    url: "https://www.mcgrox.top/register?aff=QXT3ZL9JRAF5",
    baseUrl: "https://www.mcgrox.top/v1",
    badge: "全能集齐",
    badgeType: "safe",
    tags: ["全主流覆盖", "长期稳定", "低门槛", "注册送额"],
    desc: "集齐主流厂商大模型的全能型中转站点，支持各类热门生态工具与聊天客户端。",
    freePerk: "注册送额度，全系列模型任意选用"
  },
  {
    id: 34,
    name: "吾爱 AI (WQDSJHAO)",
    category: "featured",
    url: "https://wqdsjhaoai.site/sign-up?aff=4zxB",
    baseUrl: "https://wqdsjhaoai.site/v1",
    badge: "社区福利",
    badgeType: "hot",
    tags: ["社区互助", "新手礼包", "简易集成", "注册送额"],
    desc: "带有浓厚社区互助色彩的赠额 API 平台，新手礼包厚道，集成说明简单详尽。",
    freePerk: "注册赠送大份新人礼包，社区交流互助氛围浓厚"
  },
  {
    id: 35,
    name: "Token-X",
    category: "featured",
    url: "https://token-x.com/sign-up?aff=ACof",
    baseUrl: "https://token-x.com/v1",
    badge: "大额奖励",
    badgeType: "hot",
    tags: ["下一代平台", "兑换码福利", "大额奖励", "注册送额"],
    desc: "功能强大的下一代 Token 聚合分发站，经常发放丰厚兑换码与活动奖励，白嫖党乐园。",
    freePerk: "注册即送充沛奖励，支持多种兑换与活动翻倍"
  },
  {
    id: 36,
    name: "探爱 API (TanAiDe)",
    category: "drawing",
    url: "https://api.tanaide.com/register?aff=M3GZBWS5VY46",
    baseUrl: "https://api.tanaide.com/v1",
    badge: "多模态语音",
    badgeType: "cute",
    tags: ["多模态", "语音交互", "低费率", "绘图"],
    desc: "不仅支持常见的大语言模型，还包含语音合成与多模态绘图模型，费率非常亲民。",
    freePerk: "注册赠送测试额度，多模态玩法任你探索"
  },
  {
    id: 37,
    name: "GoRun API",
    category: "api",
    url: "https://api.gorun.cc/sign-up?aff=KHRA",
    baseUrl: "https://api.gorun.cc/v1",
    badge: "并发优化",
    badgeType: "speed",
    tags: ["自动化适配", "并发优化", "高并发", "快速响应"],
    desc: "专为自动化脚本、批处理任务与后台微服务优化的快速通道，稳定性值得信赖。",
    freePerk: "注册即送免费额度，脚本批量调用好帮手"
  },
  {
    id: 38,
    name: "Sivyer API",
    category: "api",
    url: "https://www.sivyer.cc/sign-up?aff=cuYx",
    baseUrl: "https://www.sivyer.cc/v1",
    badge: "超长文本",
    badgeType: "safe",
    tags: ["长文本处理", "私有化稳定", "长文本", "Claude-3.5"],
    desc: "擅长长文本上下文分析的高可用接口，适合小说创作、研报精读以及大部头代码分析。",
    freePerk: "注册即送启动金，长文本解析不截断"
  },
  {
    id: 39,
    name: "FlowBee (蜜蜂API)",
    category: "coding",
    url: "https://flowbee.top/sign-up?aff=vRp2",
    baseUrl: "https://flowbee.top/v1",
    badge: "工作流首选",
    badgeType: "code",
    tags: ["Dify工作流", "LangChain", "自动化引擎", "Cursor可用"],
    desc: "与 Dify、FastGPT、LangChain 等工作流平台天作之合，专为构建 AI 应用定制。",
    freePerk: "注册即领体验包，无缝嵌入各类 AI Agent 工作流"
  },
  {
    id: 40,
    name: "B.AI Chat",
    category: "chat",
    url: "https://chat.b.ai/chat?invite_code=JYYZK2",
    baseUrl: "https://chat.b.ai",
    badge: "开箱即聊",
    badgeType: "web",
    tags: ["Web免配置", "精美对话", "免配置", "即开即聊"],
    desc: "极简优雅的在线 Web 聊天室，界面直观，适合不想折腾客户端配置的纯对话用户。",
    freePerk: "邀请注册即送免费对话次数，免装任何客户端"
  },
  {
    id: 41,
    name: "KSCSNK AI",
    category: "fast",
    url: "https://ai.kscsnkli.site/sign-up?aff=3AcK",
    baseUrl: "https://ai.kscsnkli.site/v1",
    badge: "新人专属",
    badgeType: "speed",
    tags: ["新人专属", "快速上手", "轻量直连", "注册送额"],
    desc: "轻巧实用的新手向 API 中转站，注册流程极短，一分钟内即可完成账号申请并拿到 Key。",
    freePerk: "新人专享免费试用额度，快速上手无压力"
  },
  {
    id: 42,
    name: "VCNO API",
    category: "featured",
    url: "https://sub.vcnovb.cn/register?aff=7NU8CEFEK793",
    baseUrl: "https://sub.vcnovb.cn/v1",
    badge: "大额试用",
    badgeType: "hot",
    tags: ["注册送额", "大额试用", "多节点负载", "超低费率"],
    desc: "多节点智能负载的高质量中转平台，注册即赠大额免费试用配额，实惠耐用。",
    freePerk: "注册立得丰厚体验额度，多节点并发负载均衡"
  },
  {
    id: 43,
    name: "辉辉云 API",
    category: "fast",
    url: "https://api.huihuiyun.top/register?aff=MR452T4ETRCC",
    baseUrl: "https://api.huihuiyun.top/v1",
    badge: "国内高速",
    badgeType: "speed",
    tags: ["国内高速", "云边协同", "国内直连", "新手友好"],
    desc: "针对国内网络环境深度优化的云端 API 平台，免翻直连，延迟极低，小白也能轻松驾驭。",
    freePerk: "注册送额度，全天候高速直连无阻碍"
  },
  {
    id: 44,
    name: "AnyModel",
    category: "featured",
    url: "https://anymodel.org/?ref=UQZSWQY",
    baseUrl: "https://anymodel.org",
    badge: "全模型对比",
    badgeType: "web",
    tags: ["全模型对比", "开源闭源齐聚", "Web免配置", "多模型聚合"],
    desc: "全球开源与闭源顶流模型的大聚合竞技场，同一页面直接横向对比各大模型的回答效果！",
    freePerk: "免翻直连，注册即享多模型无缝比对体验"
  }
];
