/**
 * Neko的AI白嫖指南 - 站点数据库
 * 整理日期: 2026
 * 包含46个优质AI大模型API中转、免费对话与白嫖额度站点
 */

const SITE_CATEGORIES = {
  all: { name: "全部站点", icon: "🐾" },
  featured: { name: "🌟 精选爆款", icon: "🎁" },
  api: { name: "⚡ API中转站", icon: "⚡" },
  coding: { name: "💻 代码专精", icon: "💻" },
  chat: { name: "💬 免配置直聊", icon: "💬" },
  drawing: { name: "🎨 绘图与创意", icon: "🎨" },
  fast: { name: "🌐 高速直连", icon: "🚀" },
};

const HOT_TAGS = [
  "注册送额",
  "每日签到",
  "GPT-4o",
  "Claude-3.5",
  "Cursor可用",
  "Web免配置",
  "二次元绘图",
  "国内直连",
  "多模型聚合",
  "超低费率",
  "高并发",
  "长文本",
];

const SITES_DATA = [
  {
    id: 1,
    name: "AgentRouter",
    category: "api",
    url: "https://agentrouter.org/register?aff=5OIh",
    baseUrl: "https://agentrouter.org/v1",
    badge: "智能体专选",
    badgeType: "hot",
    tags: ["注册送额", "多模型聚合", "高并发", "Agent专供"],
    desc: "智能体专属网关，多模型热备，毫秒级路由。",
    freePerk: "注册即送初始额度，支持全系主力模型"
  },
  {
    id: 2,
    name: "JustWoker API",
    category: "api",
    url: "https://api.justwoker.icu/register?aff=8ygR",
    baseUrl: "https://api.justwoker.icu/v1",
    badge: "轻量极速",
    badgeType: "speed",
    tags: ["NewAPI", "轻量快速", "开发者友好", "国内直连"],
    desc: "轻量稳定 NewAPI 平台，开箱即用，延迟低。",
    freePerk: "注册送免费测试 Token"
  },
  {
    id: 3,
    name: "GoRouter",
    category: "api",
    url: "https://gorouter.app/sign-up?aff=woTg",
    baseUrl: "https://gorouter.app/v1",
    badge: "全球加速",
    badgeType: "speed",
    tags: ["全球加速", "企业级并发", "高可用", "多模型聚合"],
    desc: "全球多节点路由加速，企业级高并发高可用。",
    freePerk: "注册送体验金，全球节点智能就近接入"
  },
  {
    id: 4,
    name: "TabiToken",
    category: "fast",
    url: "https://tabitoken.com/sign-up?aff=Zknh",
    baseUrl: "https://tabitoken.com/v1",
    badge: "新人礼包",
    badgeType: "hot",
    tags: ["Token分发", "超低费率", "新人礼包", "注册送额"],
    desc: "高性价比 Token 分发与中转，新手零门槛。",
    freePerk: "注册即送启动额度包，绑定即用"
  },
  {
    id: 5,
    name: "福卡 API (FuKa)",
    category: "api",
    url: "https://api.fuka.win/sign-up?",
    baseUrl: "https://api.fuka.win/v1",
    badge: "口碑公益",
    badgeType: "free",
    tags: ["公益优选", "全模型支持", "性价比", "GPT-4o"],
    desc: "高口碑平价与公益中转，主流大模型覆盖全。",
    freePerk: "注册即送新手配额，全系列随心测"
  },
  {
    id: 6,
    name: "猫猫 API (CatCat)",
    category: "api",
    url: "https://api.catcat.top/sign-up?aff=SNTc",
    baseUrl: "https://api.catcat.top/v1",
    badge: "萌系稳定",
    badgeType: "cute",
    tags: ["萌系稳定", "Claude-3.5", "极速响应", "注册送额"],
    desc: "萌系二次元中转站，响应极快，通道稳定。",
    freePerk: "注册享初始免费额度，Claude 3.5 丝滑"
  },
  {
    id: 7,
    name: "HCNsec API",
    category: "fast",
    url: "https://api.hcnsec.cn/sign-up?aff=nJQnaff=KSK9",
    baseUrl: "https://api.hcnsec.cn/v1",
    badge: "安全高防",
    badgeType: "safe",
    tags: ["安全防护", "国内直连", "多协议", "稳定可靠"],
    desc: "高防安全防护与国内高速直连，稳定不掉线。",
    freePerk: "注册送新手测试额度，直连低延迟"
  },
  {
    id: 8,
    name: "SharedChat",
    category: "chat",
    url: "https://new.sharedchat.cc/list/#/register?i=4l71o",
    baseUrl: "https://new.sharedchat.cc",
    badge: "免配置直聊",
    badgeType: "web",
    tags: ["Web免配置", "ChatGPT共享", "多账号", "开箱即用"],
    desc: "网页版大模型账号池共享，免客户端直接聊。",
    freePerk: "注册送免费对话次数，免自备 Key"
  },
  {
    id: 9,
    name: "洛谷 AI (Luogu)",
    category: "coding",
    url: "https://ai.luogu.me/sign-up?aff=KI3Z",
    baseUrl: "https://ai.luogu.me/v1",
    badge: "算法编程",
    badgeType: "code",
    tags: ["算法编程", "代码补全", "Cursor可用", "学术生态"],
    desc: "算法竞赛与开发者专属高质量代码模型镜像。",
    freePerk: "注册送额度，代码调试与学术优选"
  },
  {
    id: 10,
    name: "丑猫 API (UglyCat)",
    category: "api",
    url: "https://api.uglycat.cc/register?aff=iyZz",
    baseUrl: "https://api.uglycat.cc/v1",
    badge: "极低延迟",
    badgeType: "speed",
    tags: ["高并发", "GPT-4o", "Claude-3.5", "极速响应"],
    desc: "超低延迟高并发，支持各种最新旗舰顶模。",
    freePerk: "注册立享体验金，支持高并发并发调用"
  },
  {
    id: 11,
    name: "北执 API (Sylu)",
    category: "fast",
    url: "https://beizhi.sylu.cc/sign-up?aff=IBxl",
    baseUrl: "https://beizhi.sylu.cc/v1",
    badge: "高校公益",
    badgeType: "free",
    tags: ["高校社区", "稳定长效", "公益赞助", "国内直连"],
    desc: "高校社区联合维护的长效公益站，良心稳定。",
    freePerk: "长期提供公益免费测试额度"
  },
  {
    id: 12,
    name: "BlueSMinds API",
    category: "fast",
    url: "https://api.bluesminds.com/sign-up?aff=uanj",
    baseUrl: "https://api.bluesminds.com/v1",
    badge: "多模态专区",
    badgeType: "safe",
    tags: ["多模态", "高防集群", "智能路由", "长文本"],
    desc: "分布式高防集群，支持 Vision 视觉与长文本。",
    freePerk: "新用户注册享大额试用额度"
  },
  {
    id: 13,
    name: "HelpCoder",
    category: "coding",
    url: "https://helpcoder.cc/register?aff=jUgZ",
    baseUrl: "https://helpcoder.cc/v1",
    badge: "代码神器",
    badgeType: "code",
    tags: ["Cursor可用", "编程助手", "代码生成", "Claude-3.5"],
    desc: "Cursor 与 VS Code 专属高吞吐代码 API。",
    freePerk: "注册送额度，完美适配 Cursor 补全"
  },
  {
    id: 14,
    name: "新建鸭 (XinJianYa)",
    category: "featured",
    url: "https://new.xinjianya.top/register?aff=96Oh",
    baseUrl: "https://new.xinjianya.top/v1",
    badge: "每日签到",
    badgeType: "hot",
    tags: ["每日签到", "注册送额", "全网低价", "超低费率"],
    desc: "每日签到领额度，长久运营，价格极低。",
    freePerk: "注册送初始额度 + 每天签到免费领"
  },
  {
    id: 15,
    name: "SupXH Free API",
    category: "featured",
    url: "https://free.supxh.xin/register?code=UEPUUR",
    baseUrl: "https://free.supxh.xin/v1",
    badge: "纯白嫖站",
    badgeType: "free",
    tags: ["纯白嫖专区", "零门槛", "注册送额", "每日签到"],
    desc: "零门槛纯免费白嫖平台，免复杂认证直接用。",
    freePerk: "输入邀请码立得大额免费额度"
  },
  {
    id: 16,
    name: "True-SOTA",
    category: "api",
    url: "https://true-sota.com/register?aff=Q3C4T6PUQLDL",
    baseUrl: "https://true-sota.com/v1",
    badge: "SOTA顶尖",
    badgeType: "speed",
    tags: ["SOTA顶模", "前沿推理", "科研首选", "Claude-3.5"],
    desc: "聚焦全球前沿顶模，深度推理与科研首选。",
    freePerk: "注册送额体验顶尖 SOTA 推理模型"
  },
  {
    id: 17,
    name: "今夕 API (JinShi)",
    category: "fast",
    url: "https://new.jinshi.xin/sign-up?aff=6oB2",
    baseUrl: "https://new.jinshi.xin/v1",
    badge: "线路冗余",
    badgeType: "safe",
    tags: ["多线路负载", "稳定持久", "开箱即用", "国内直连"],
    desc: "多线路负载均衡，拒绝断连，日常主力超稳。",
    freePerk: "注册获赠使用额度，一键配置"
  },
  {
    id: 18,
    name: "CamelHub",
    category: "api",
    url: "https://api.camel-hub.com/register?aff=TO1b",
    baseUrl: "https://api.camel-hub.com/v1",
    badge: "Agent适配",
    badgeType: "code",
    tags: ["Agent协作", "开发套件", "高并发", "多模型聚合"],
    desc: "多智能体协同与复杂开发架构深度优化网关。",
    freePerk: "注册立享开发者福利包"
  },
  {
    id: 19,
    name: "网易云风 (WYY22)",
    category: "fast",
    url: "https://www.wyy22.com/sign-up?aff=YZL3",
    baseUrl: "https://www.wyy22.com/v1",
    badge: "小白友好",
    badgeType: "free",
    tags: ["公益普惠", "新手友好", "NextChat适配", "国内直连"],
    desc: "极清新新手友好中转，填 Key 即可秒速开聊。",
    freePerk: "新手注册即领赠额，免翻直连"
  },
  {
    id: 20,
    name: "NexusVAI",
    category: "chat",
    url: "https://www.nexusvai.xyz/chat/?invite=1509213c-2c4a-4b10-9626-fa8689d4795f",
    baseUrl: "https://www.nexusvai.xyz",
    badge: "全能工作台",
    badgeType: "web",
    tags: ["Web免配置", "网页直接聊", "多模型切换", "智能对话"],
    desc: "现代在线对话工作台，免本地配置，开箱即聊。",
    freePerk: "邀请直达注册，免客户端开箱直接聊"
  },
  {
    id: 21,
    name: "7891VIP",
    category: "drawing",
    url: "https://7891vip.cc.cd/login?view=reg&aff=gioR",
    baseUrl: "https://7891vip.cc.cd/v1",
    badge: "VIP特权",
    badgeType: "hot",
    tags: ["VIP尊享", "超大带宽", "逆向官转", "长文本"],
    desc: "超大带宽 VIP 通道，涵盖官转与精细逆向接口。",
    freePerk: "注册享高优先级通道与初始赠额"
  },
  {
    id: 22,
    name: "Rinko AI (NAI)",
    category: "drawing",
    url: "https://nai.rinko.ai/sign-up?aff=Fr7j",
    baseUrl: "https://nai.rinko.ai/v1",
    badge: "二次元生图",
    badgeType: "cute",
    tags: ["二次元绘图", "NovelAI专精", "动漫生图", "绘画"],
    desc: "专注 NovelAI 二次元动漫绘图，画质惊艳细腻。",
    freePerk: "注册送生图积分，动漫画师狂喜"
  },
  {
    id: 23,
    name: "Orevx AI",
    category: "chat",
    url: "https://orevx.ai/login?mode=register&inviteCode=NWO170LO",
    baseUrl: "https://orevx.ai",
    badge: "现代交互",
    badgeType: "web",
    tags: ["Web免配置", "文档分析", "全能助手", "长文本"],
    desc: "现代企业级对话助手，支持长文档与多模态分析。",
    freePerk: "输入邀请码注册，立享丰富对话额度"
  },
  {
    id: 24,
    name: "TokenBom (Token炸弹)",
    category: "featured",
    url: "https://tokenbom.com/login?mode=register&invite=SS-9B89C913",
    baseUrl: "https://tokenbom.com/v1",
    badge: "福利爆仓",
    badgeType: "hot",
    tags: ["注册送额", "大额赠送", "海量Token", "福利爆仓"],
    desc: "Token 投弹手！注册赠额丰厚，活动多超划算。",
    freePerk: "注册送大额体验礼包，真正吃到饱"
  },
  {
    id: 25,
    name: "CreitAPI",
    category: "drawing",
    url: "https://myapi.creitingameplays.com/sign-up?aff=oV4h",
    baseUrl: "https://myapi.creitingameplays.com/v1",
    badge: "极客游戏",
    badgeType: "code",
    tags: ["极客专用", "游戏NPC", "低延迟", "多模型聚合"],
    desc: "针对游戏 NPC、剧情互动优化的特色轻中转。",
    freePerk: "注册送体验金，适合游戏与剧情脚本"
  },
  {
    id: 26,
    name: "NOFX One",
    category: "chat",
    url: "https://nofx.one/zh-CN/sign-in?ref=17AE4SJY",
    baseUrl: "https://nofx.one",
    badge: "中文工作台",
    badgeType: "web",
    tags: ["Web免配置", "一体化平台", "网页直接聊", "中文界面"],
    desc: "本土化 Web AI 对话工作台，界面精美免配置。",
    freePerk: "注册即送额度，免客户端开箱即用"
  },
  {
    id: 27,
    name: "KK Token",
    category: "fast",
    url: "https://kktoken.cc/sign-up?aff=5eUk",
    baseUrl: "https://kktoken.cc/v1",
    badge: "极速响应",
    badgeType: "speed",
    tags: ["极简轻量", "分发稳定", "快速到账", "超低费率"],
    desc: "轻量 Token 分发节点，直奔主题，极速生成 Key。",
    freePerk: "注册即领试用配额，轻量好用"
  },
  {
    id: 28,
    name: "AeroLink",
    category: "fast",
    url: "https://aerolink.lat/register?ref=ZY8-XVA",
    baseUrl: "https://aerolink.lat/v1",
    badge: "跨境专线",
    badgeType: "speed",
    tags: ["海外加速", "跨境专线", "网络优化", "低抖动"],
    desc: "专线直达官方端点，网络极低抖动，输出稳定。",
    freePerk: "注册即送免费额度，体验专线加速"
  },
  {
    id: 29,
    name: "CheapCodex",
    category: "coding",
    url: "https://api.cheapcodex.online/register?aff=NRS3ZWZLHSZN",
    baseUrl: "https://api.cheapcodex.online/v1",
    badge: "超平价代码",
    badgeType: "code",
    tags: ["超平价代码", "Cursor可用", "Claude-Code", "极速补全"],
    desc: "代码专精平价服务，完美适配各类 IDE 插件。",
    freePerk: "注册送代码测试额度，写代码极丝滑"
  },
  {
    id: 30,
    name: "Denxio API",
    category: "api",
    url: "https://api.denxio.top/register?invite_code=JZD9ERE7GV4C",
    baseUrl: "https://api.denxio.top/v1",
    badge: "热备网关",
    badgeType: "safe",
    tags: ["聚合网关", "多渠道热备", "高可用", "高并发"],
    desc: "多渠道热备容灾聚合网关，秒级自动故障切换。",
    freePerk: "注册送大额额度，高并发不掉线"
  },
  {
    id: 31,
    name: "Vyce AI",
    category: "chat",
    url: "https://vyceai.com/signup?ref=VYCE_WPT6BH",
    baseUrl: "https://vyceai.com",
    badge: "前沿UI",
    badgeType: "web",
    tags: ["Web免配置", "前沿UI", "创意灵感", "智能工作流"],
    desc: "设计感爆棚的 AI 创作中心，视觉极具科技感。",
    freePerk: "注册即享专属免费点数，直接开聊"
  },
  {
    id: 32,
    name: "KiosAPI",
    category: "api",
    url: "https://kiosapi.com/sign-up?aff=KhTb",
    baseUrl: "https://kiosapi.com/v1",
    badge: "企业级吞吐",
    badgeType: "speed",
    tags: ["企业级吞吐", "极速响应", "稳定输出", "GPT-4o"],
    desc: "企业级吞吐能力，首字延迟低，支持超多并发。",
    freePerk: "注册即可白嫖高并发体验金"
  },
  {
    id: 33,
    name: "McGrox",
    category: "fast",
    url: "https://www.mcgrox.top/register?aff=QXT3ZL9JRAF5",
    baseUrl: "https://www.mcgrox.top/v1",
    badge: "全能集齐",
    badgeType: "safe",
    tags: ["全主流覆盖", "长期稳定", "低门槛", "注册送额"],
    desc: "集齐主流厂商模型的全能中转，生态适配全面。",
    freePerk: "注册送额度，主流模型任意选用"
  },
  {
    id: 34,
    name: "吾爱 AI (WQDSJHAO)",
    category: "featured",
    url: "https://wqdsjhaoai.site/sign-up?aff=4zxB",
    baseUrl: "https://wqdsjhaoai.site/v1",
    badge: "社区福利",
    badgeType: "hot",
    tags: ["社区互助", "新手礼包", "简易集成", "注册送额"],
    desc: "社区互助氛围浓厚，新手礼包足，简单易集成。",
    freePerk: "注册即赠丰厚新手礼包"
  },
  {
    id: 35,
    name: "Token-X",
    category: "featured",
    url: "https://token-x.com/sign-up?aff=ACof",
    baseUrl: "https://token-x.com/v1",
    badge: "大额奖励",
    badgeType: "hot",
    tags: ["下一代平台", "兑换码福利", "大额奖励", "注册送额"],
    desc: "下一代 Token 分发站，常发兑换码与活动奖励。",
    freePerk: "注册即送充沛奖励，兑换活动丰富"
  },
  {
    id: 36,
    name: "探爱 API (TanAiDe)",
    category: "drawing",
    url: "https://api.tanaide.com/register?aff=M3GZBWS5VY46",
    baseUrl: "https://api.tanaide.com/v1",
    badge: "多模态语音",
    badgeType: "cute",
    tags: ["多模态", "语音交互", "低费率", "绘图"],
    desc: "支持语音、图像与文本的多模态性价比中转。",
    freePerk: "注册送测试额度，多模态玩法齐备"
  },
  {
    id: 37,
    name: "GoRun API",
    category: "api",
    url: "https://api.gorun.cc/sign-up?aff=KHRA",
    baseUrl: "https://api.gorun.cc/v1",
    badge: "并发优化",
    badgeType: "speed",
    tags: ["自动化适配", "并发优化", "高并发", "快速响应"],
    desc: "专为脚本自动化与批处理优化的快速通道。",
    freePerk: "注册送免费额度，自动化脚本首选"
  },
  {
    id: 38,
    name: "Sivyer API",
    category: "api",
    url: "https://www.sivyer.cc/sign-up?aff=cuYx",
    baseUrl: "https://www.sivyer.cc/v1",
    badge: "超长文本",
    badgeType: "safe",
    tags: ["长文本处理", "私有化稳定", "长文本", "Claude-3.5"],
    desc: "擅长长文本上下文分析，长篇创作不截断。",
    freePerk: "注册即送启动金，长文档解析力强"
  },
  {
    id: 39,
    name: "FlowBee (蜜蜂API)",
    category: "coding",
    url: "https://flowbee.top/sign-up?aff=vRp2",
    baseUrl: "https://flowbee.top/v1",
    badge: "工作流首选",
    badgeType: "code",
    tags: ["Dify工作流", "LangChain", "自动化引擎", "Cursor可用"],
    desc: "对接 Dify、FastGPT 与 LangChain 工作流首选。",
    freePerk: "注册即领体验包，无缝嵌入 Agent"
  },
  {
    id: 40,
    name: "B.AI Chat",
    category: "chat",
    url: "https://chat.b.ai/chat?invite_code=JYYZK2",
    baseUrl: "https://chat.b.ai",
    badge: "开箱即聊",
    badgeType: "web",
    tags: ["Web免配置", "精美对话", "免配置", "即开即聊"],
    desc: "极简美观在线聊天室，免去一切本地配置。",
    freePerk: "邀请注册即送免费对话次数"
  },
  {
    id: 41,
    name: "KSCSNK AI",
    category: "fast",
    url: "https://ai.kscsnkli.site/sign-up?aff=3AcK",
    baseUrl: "https://ai.kscsnkli.site/v1",
    badge: "新人专属",
    badgeType: "speed",
    tags: ["新人专属", "快速上手", "轻量直连", "注册送额"],
    desc: "流程精简的新手向站点，一分钟拿 Key 上手。",
    freePerk: "新人专享免费试用额度"
  },
  {
    id: 42,
    name: "VCNO API",
    category: "featured",
    url: "https://sub.vcnovb.cn/register?aff=7NU8CEFEK793",
    baseUrl: "https://sub.vcnovb.cn/v1",
    badge: "大额试用",
    badgeType: "hot",
    tags: ["注册送额", "大额试用", "多节点负载", "超低费率"],
    desc: "多节点智能负载，注册即送大额免费试用。",
    freePerk: "注册立得丰厚试用额度"
  },
  {
    id: 43,
    name: "辉辉云 API",
    category: "fast",
    url: "https://api.huihuiyun.top/register?aff=MR452T4ETRCC",
    baseUrl: "https://api.huihuiyun.top/v1",
    badge: "国内高速",
    badgeType: "speed",
    tags: ["国内高速", "云边协同", "国内直连", "新手友好"],
    desc: "国内网络极佳的高速云端 API，免翻直连超低延迟。",
    freePerk: "注册送额度，全天候高速直连"
  },
  {
    id: 44,
    name: "AnyModel",
    category: "featured",
    url: "https://anymodel.org/?ref=UQZSWQY",
    baseUrl: "https://anymodel.org",
    badge: "全模型对比",
    badgeType: "web",
    tags: ["全模型对比", "开源闭源齐聚", "Web免配置", "多模型聚合"],
    desc: "全球开源与闭源顶模大聚合，同一页横向对比。",
    freePerk: "免翻直连，注册享多模型比对"
  },
  {
    id: 45,
    name: "XXS API (小学生)",
    category: "api",
    url: "https://xxs.l.cd/sign-up?aff=yrJv",
    baseUrl: "https://xxs.l.cd/v1",
    badge: "轻量低价",
    badgeType: "speed",
    tags: ["NewAPI", "轻量快速", "超低费率", "注册送额"],
    desc: "轻量高性价比 NewAPI 站点，响应快费率低。",
    freePerk: "注册即送初始额度，费率超亲民"
  },
  {
    id: 46,
    name: "0168 AI",
    category: "fast",
    url: "https://0168.cn/recommend/J6U7hMQmuTVF",
    baseUrl: "https://0168.cn/v1",
    badge: "聚合直连",
    badgeType: "hot",
    tags: ["多模型聚合", "国内直连", "综合工作台", "注册送额"],
    desc: "综合大模型聚合服务，国内高速免翻直连。",
    freePerk: "注册领体验礼包，免翻直连顺畅"
  }
];
